# Generated by Django 3.2.3 on 2021-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultdetail',
            name='fault_date',
            field=models.CharField(max_length=20),
        ),
    ]
