# Generated by Django 3.2.3 on 2021-05-27 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_alter_faultdetail_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultdetail',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
