# Generated by Django 3.2.3 on 2021-05-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_faultdetail_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
